config:
  validation: true
  warningsAsErrors: true

naming:
  FunctionNaming:
    functionPattern: '[A-Za-z][a-zA-Z0-9]*'
  MatchingDeclarationName:
    active: false
  PackageNaming:
    packagePattern: '[a-z_]+(\.[a-z_][A-Za-z0-9_]*)*'

complexity:
  CyclomaticComplexMethod:
    active: false
  LargeClass:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false

style:
  DestructuringDeclarationWithTooManyEntries:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
  UnusedPrivateMember:
    allowedNames: '.*Preview'
